src/HatueySoft/SecurityBundle/Entity/User.php
<?php

namespace HatueySoft\SecurityBundle\Entity;

use FOS\UserBundle\Model\User as BaseUser;
use Doctrine\ORM\Mapping as ORM;
use HatueySoft\SecurityBundle\Validator\Constraints\UniqueSystemUserEmail;
use HatueySoft\SecurityBundle\Validator\Constraints\UniqueSystemUserUsername;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Buseta\BusesBundle\Entity\GrupoBuses;

/**
 * @author: firomero <firomerorom4@gmail.com>
 * @author: dundivet <dundivet@emailn.de>
 *
 * @ORM\Entity(repositoryClass="HatueySoft\SecurityBundle\Entity\UserRepository")
 * @ORM\Table(name="hatueysoft_security_user")
 * @UniqueEntity(fields={"username", "email"})
 * @UniqueSystemUserUsername()
 * @UniqueSystemUserEmail()
 */
class User extends BaseUser
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @var string
     */
    protected $username;

    /**
     * @var string
     */
    protected $email;

    /**
     * @ORM\ManyToMany(targetEntity="HatueySoft\SecurityBundle\Entity\Group")
     * @ORM\JoinTable(name="hatueysoft_security_users_groups",
     *      joinColumns={@ORM\JoinColumn(name="user_id", referencedColumnName="id")},
     *      inverseJoinColumns={@ORM\JoinColumn(name="group_id", referencedColumnName="id")}
     * )
     */
    protected $groups;

    /**
     * @ORM\ManyToMany(targetEntity="HatueySoft\TicketBundle\Entity\Proyecto")
     * @ORM\JoinTable(name="usuario_proyecto",
     *      joinColumns={@ORM\JoinColumn(name="user_id", referencedColumnName="id")},
     *      inverseJoinColumns={@ORM\JoinColumn(name="proyecto_id", referencedColumnName="id")}
     * )
     */
    private $proyectos;

    /**
     * @var string
     *
     * @ORM\Column(name="nombres", type="string", length=64)
     * @Assert\NotBlank
     */
    private $nombres;

    /**
     * @var string
     *
     * @ORM\Column(name="apellidos", type="string", length=64, nullable=true)
     */
    private $apellidos;

    /**
     * @var \HatueySoft\UploadBundle\Entity\UploadResources
     *
     * @ORM\OneToOne(targetEntity="HatueySoft\UploadBundle\Entity\UploadResources", cascade={"persist", "remove"})
     */
    private $foto;

    /**
     * @var string
     *
     * @ORM\Column(name="pin", type="string", length=4, nullable=true)
     */
    private $pin;


    function __construct()
    {
        parent::__construct();

        $this->enabled = true;
        $this->proyectos = new \Doctrine\Common\Collections\ArrayCollection();
    }


    public function isActive()
    {
        return $this->locked == false;
    }

    public function setActive($value)
    {
        $this->locked = !$value;
    }

    public function getId()
    {
        return $this->id;
    }

    /**
     * @return mixed
     */
    public function getNombres()
    {
        return $this->nombres;
    }

    /**
     * @param mixed $nombres
     */
    public function setNombres($nombres)
    {
        $this->nombres = $nombres;
    }

    /**
     * @return string
     */
    public function getApellidos()
    {
        return $this->apellidos;
    }

    /**
     * @param string $apellidos
     */
    public function setApellidos($apellidos)
    {
        $this->apellidos = $apellidos;
    }

    /**
     * @return mixed
     */
    public function getFoto()
    {
        return $this->foto;
    }

    /**
     * @param mixed $foto
     */
    public function setFoto($foto)
    {
        $this->foto = $foto;
    }

    /**
     * @return string
     */
    public function getPin()
    {
        return $this->pin;
    }

    /**
     * @param string $pin
     */
    public function setPin($pin)
    {
        $this->pin = $pin;
    }

    public function getNombreCompleto()
    {
        return sprintf('%s %s', $this->getNombres(), $this->getApellidos());
    }

    /**
     * Get proyectos
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getProyectos()
    {
        return $this->proyectos;
    }

    /**
     * Add proyecto
     *
     * @param \HatueySoft\TicketBundle\Entity\Proyecto $proyectos
     * @return User
     */
    public function addProyecto(\HatueySoft\TicketBundle\Entity\Proyecto $proyectos)
    {
        $this->proyectos[] = $proyectos;

        return $this;
    }

    /**
     * Remove proyectos
     *
     * @param \HatueySoft\TicketBundle\Entity\Proyecto $proyectos
     */
    public function removeUsuario(\HatueySoft\TicketBundle\Entity\Proyecto $proyectos)
    {
        $this->proyectos->removeElement($proyectos);
    }
}

src/HatueySoft/SecurityBundle/Controller/UsuarioController.php
<?php

namespace HatueySoft\SecurityBundle\Controller;

use Doctrine\Common\Collections\ArrayCollection;
use HatueySoft\SecurityBundle\Form\Model\UserModel;
use Symfony\Component\Form\FormError;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use HatueySoft\SecurityBundle\Entity\User as Usuario;
use HatueySoft\SecurityBundle\Form\Type\UsuarioType as UsuarioType;

/**
 * Usuario controller.
 *
 * @Route("/usuario")
 */
class UsuarioController extends Controller
{

    /**
     * Lists all Usuario entities.
     *
     * @Route("/", name="security_usuario")
     */
    public function indexAction()
    {
        $em = $this->getDoctrine()->getManager();

        $entities = $em->getRepository('HatueySoftSecurityBundle:User')->findAll();

        return $this->render('HatueySoftSecurityBundle:Usuario:index.html.twig', array(
            'entities' => $entities,
        ));
    }
    /**
     * Creates a new Usuario entity.
     *
     * @Route("/create", name="security_usuario_create")
     * @Method("POST")
     */
    public function createAction(Request $request)
    {
        $model = new UserModel();
        $form = $this->createCreateForm($model);
        $form->handleRequest($request);

        if ($form->isValid()) {
            $user = new Usuario();

            $user->setUsername($model->getUsername());
            $user->setEmail($model->getEmail());
            $user->setNombres($model->getNombres());
            $user->setApellidos($model->getApellidos());
            $user->setRoles($model->getRoles());
            $user->setPlainPassword($model->getPlainPassword());

            $userManager    = $this->get('fos_user.user_manager');

            try {
                $this->get('session')->getFlashBag()->add('success', 'Se ha creado el usuario satisfactoriamente.');

                $userManager->updateUser($user);

                return $this->redirect($this->generateUrl('security_usuario_show', array('id' => $user->getId())));
            } catch (\Exception $e) {
                $this->get('logger')->critical(sprintf('Ha ocurrido un error al crear el usuario. Detalles: %s', $e->getMessage()));
                $this->get('session')->getFlashBag()->add('danger', 'Ha ocurrido un error al crear el usuario.');
            }
        }

        return $this->render('HatueySoftSecurityBundle:Usuario:new.html.twig', array(
            'form'   => $form->createView(),
        ));
    }

    /**
     * Creates a form to create a Usuario entity.
     *
     * @param Usuario $model The entity
     *
     * @return \Symfony\Component\Form\Form The form
     */
    private function createCreateForm(UserModel $model = null)
    {
        $form = $this->createForm('hatueysoft_security_usuario_type', $model, array(
            'action' => $this->generateUrl('security_usuario_create'),
            'method' => 'POST',
        ));

        return $form;
    }

    /**
     * Displays a form to create a new Usuario entity.
     *
     * @Route("/new", name="security_usuario_new")
     */
    public function newAction()
    {
        $form   = $this->createCreateForm(new UserModel());

        return $this->render('HatueySoftSecurityBundle:Usuario:new.html.twig', array(
            'form'   => $form->createView(),
        ));
    }

    /**
     * Finds and displays a Usuario entity.
     *
     * @Route("/{id}/show", name="security_usuario_show")
     */
    public function showAction($id)
    {
        $em = $this->getDoctrine()->getManager();

        $entity = $em->getRepository('HatueySoftSecurityBundle:User')->find($id);

        if (!$entity) {
            throw $this->createNotFoundException('Unable to find Usuario entity.');
        }

        $deleteForm = $this->createDeleteForm($id);

        return $this->render('HatueySoftSecurityBundle:Usuario:show.html.twig', array(
            'entity'      => $entity,
            'delete_form' => $deleteForm->createView(),
        ));
    }

    /**
     * Displays a form to edit an existing Usuario entity.
     *
     * @param Usuario $user
     *
     * @return \Symfony\Component\HttpFoundation\Response
     *
     * @Route("/{id}/edit", name="security_usuario_edit")
     */
    public function editAction(Usuario $user)
    {
        $editForm = $this->createEditForm(new UserModel($user));
        $deleteForm = $this->createDeleteForm($user->getId());

        return $this->render('HatueySoftSecurityBundle:Usuario:edit.html.twig', array(
            'entity'      => $user,
            'edit_form'   => $editForm->createView(),
            'delete_form' => $deleteForm->createView(),
        ));
    }

    /**
    * Creates a form to edit a Usuario entity.
    *
    * @param UserModel $model The entity
    *
    * @return \Symfony\Component\Form\Form The form
    */
    private function createEditForm(UserModel $model)
    {
        $form = $this->createForm('hatueysoft_security_usuario_type', $model, array(
            'action' => $this->generateUrl('security_usuario_update', array('id' => $model->getId())),
            'method' => 'PUT',
        ));

        return $form;
    }
    /**
     * Edits an existing Usuario entity.
     *
     * @Route("/{id}/update", name="security_usuario_update")
     * @Method({"POST", "PUT"})
     */
    public function updateAction(Request $request, Usuario $user)
    {
        $model = new UserModel($user);
        //$deleteForm = $this->createDeleteForm($id);
        $editForm = $this->createEditForm($model);

        $editForm->handleRequest($request);
        if ($editForm->isValid()) {
            $em = $this->get('doctrine.orm.entity_manager');
            $userManager = $this->get('fos_user.user_manager');

            $user->setNombres($model->getNombres());
            $user->setApellidos($model->getApellidos());
            $user->setEmail($model->getEmail());
            $user->setRoles($model->getRoles());

            if (0 !== strlen($model->getPlainPassword())) {
                $user->setPlainPassword($model->getPlainPassword());
                $userManager->updatePassword($user);
            }

            if (0 !== strlen($model->getPin())) {
                $user->setPin($model->getPin());
            }

            try {
                $userManager->updateUser($user);

                $this->get('session')->getFlashBag()->add('success', 'Se han editado los datos del usuario satisfactoriamente.');

                return $this->redirect($this->generateUrl('security_usuario_edit', array('id' => $user->getId())));
            } catch (\Exception $e) {
                $this->get('logger')->critical(sprintf('Ha ocurrido un error al editar los datos del usuario. Detalles: %s', $e->getMessage()));
                $this->get('session')->getFlashBag()->add('danger', 'Ha ocurrido un error al editar los datos del usuario.');
            }
        }

        return $this->render('HatueySoftSecurityBundle:Usuario:edit.html.twig', array(
            'entity'      => $user,
            'edit_form'   => $editForm->createView(),
            //'delete_form' => $deleteForm->createView(),
        ));
    }
    /**
     * Deletes a Usuario entity.
     *
     * @Route("/{id}/delete", name="security_usuario_delete")
     * @Method({"POST", "DELETE"})
     */
    public function deleteAction(Request $request, $id)
    {
        $form = $this->createDeleteForm($id);
        $form->handleRequest($request);

        if ($form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $entity = $em->getRepository('HatueySoftSecurityBundle:User')->find($id);

            if (!$entity) {
                throw $this->createNotFoundException('Unable to find Usuario entity.');
            }

            $em->remove($entity);
            $em->flush();
        }

        return $this->redirect($this->generateUrl('security_usuario'));
    }

    /**
     * Creates a form to delete a Usuario entity by id.
     *
     * @param mixed $id The entity id
     *
     * @return \Symfony\Component\Form\Form The form
     */
    private function createDeleteForm($id)
    {
        return $this->createFormBuilder()
            ->setAction($this->generateUrl('security_usuario_delete', array('id' => $id)))
            ->setMethod('DELETE')
            ->getForm()
        ;
    }

}

src/HatueySoft/SecurityBundle/Resources/views/Usuario/_form.html.twig
{{ form_start(form) }}
{{ form_row(form.username) }}
{{ form_row(form.email) }}
{{ form_row(form.nombres) }}
{{ form_row(form.apellidos) }}
{{ form_row(form.plainPassword) }}
{{ form_row(form.pin) }}
{{ form_row(form.roles) }}
{#{{ form_row(form.groups) }}#}

<br/>
<div class="btn-actions">
    <button class="btn btn-primary" type="submit"><span class="glyphicon glyphicon-save"></span> Aceptar</button>

    <a href="{{ path('security_usuario') }}" class="btn btn-default">
        <span class="glyphicon glyphicon-arrow-left"></span> Volver
    </a>
</div>
{{ form_end(form) }}

src/HatueySoft/SecurityBundle/Resources/views/Usuario/edit.html.twig
{% extends '@HatueySoftSecurity/layout.html.twig' %}

{% block title 'Usuario edit' %}

{% block headline block('title') %}

{% block tituloPagina %}
    <h1>Edit user</h1>
{% endblock %}

{% block content -%}
    {% include '@HatueySoftSecurity/Usuario/_form.html.twig' with {'form': edit_form} %}
{% endblock %}

src/HatueySoft/SecurityBundle/Resources/views/Usuario/index.html.twig
{% extends '@HatueySoftSecurity/layout.html.twig' %}

{% block title 'Usuario list' %}

{% block headline block('title') %}

{% block tituloPagina %}
    <h1>Users list</h1>
{% endblock %}

{% block content -%}

    <a href="{{ path('security_usuario_new') }}" class="btn btn-primary" style="margin-bottom: 8px;"><span class="glyphicon glyphicon-plus"></span> Adicionar</a>

    <table class="records_list table table-hover table-striped table-bordered table-condensed">
        <thead>
            <tr>
                <th>Usuario</th>
                <th>Email</th>
                <th>Nombre completo</th>
                <th>Estado</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
        {% for entity in entities %}
            <tr>
                <td><a href="{{ path('security_usuario_show', { 'id': entity.id }) }}">{{ entity.username }}</a></td>
                <td>{{ entity.email | default('-') }}</td>
                <td>{{ entity.nombreCompleto | default('-') }}</td>
                <td>{{ entity.enabled ? '<span class="glyphicon glyphicon-ok" title="Activo"></span>' : '<span class="glyphicon glyphicon-remove" title="Deshabilitado"></span>' }}</td>
                <td>
                    <a href="{{ path('security_usuario_show', { 'id': entity.id }) }}" class="btn btn-default btn-sm">
                        <span class="glyphicon glyphicon-eye-open"></span> Ver</a>
                    <a href="{{ path('security_usuario_edit', { 'id': entity.id }) }}" class="btn btn-primary btn-sm">
                        <span class="glyphicon glyphicon-pencil"></span> Editar</a>
                </td>
            </tr>
        {% else %}
        <tr><td colspan="8">No se encontraron elementos que mostrar.</td></tr>
        {% endfor %}
        </tbody>
    </table>

{% endblock %}

src/HatueySoft/SecurityBundle/Resources/views/Usuario/new.html.twig
{% extends '@HatueySoftSecurity/layout.html.twig' %}

{% block title 'Usuario creation' %}

{% block headline block('title') %}

{% block tituloPagina %}
    <h1>New user</h1>
{% endblock %}

{% block content -%}
    {% include '@HatueySoftSecurity/Usuario/_form.html.twig' with {'form': form} %}
{% endblock %}

src/HatueySoft/SecurityBundle/Resources/views/Usuario/show.html.twig
{% extends '@HatueySoftSecurity/layout.html.twig' %}

{% block title 'Usuario' %}

{% block headline block('title') %}

{% block tituloPagina %}
    <h1>Show user</h1>
{% endblock %}

{% block content -%}
    <table class="record_properties table table-striped">
        <tbody>
            <tr>
                <th>Uusario</th>
                <td>{{ entity.username }}</td>
            </tr>
            <tr>
                <th>Nombre</th>
                <td>{{ entity.nombres | default('-') }}</td>
            </tr>
            <tr>
                <th>Apellidos</th>
                <td>{{ entity.apellidos | default('-') }}</td>
            </tr>
            <tr>
                <th>Email</th>
                <td>{{ entity.email }}</td>
            </tr>
            <tr>
                <th>Roles</th>
                <td>{% for rol in entity.roles %}{{ rol }}|{% endfor %}</td>
            </tr>

            {#<tr>
                <th>Grupos</th>
                <td>{% for group in entity.groups %}{{ group }}|{% endfor %}</td>
            </tr>#}
        </tbody>
    </table>

        <div class="btn-actions">
        {{ form_start(delete_form) }}


        <a href="{{ path('security_usuario') }}" class="btn btn-default">
            <span class="glyphicon glyphicon-arrow-left"></span> Volver
        </a>

        <a href="{{ path('security_usuario_edit', { 'id': entity.id }) }}" class="btn btn-default">
            <span class="glyphicon glyphicon-pencil"></span> Editar
        </a>


        <button class="btn btn-danger" type="submit"><span class="glyphicon glyphicon-trash"></span> Eliminar</button>
            {{ form_widget(delete_form._token) }}
        {{ form_end(delete_form) }}
    </div>
{% endblock %}